################################################################################
# run_config.yml:
#   Contains config options for the Application Run:
#     corresponding default values to be updated
#
#   Loaded in:  ./initializers/zt_load_config.rb
#
#   11.10.2016  ZT  Inherited from  95km
#   30.08.2017  *access_restricted key* is added
#   22.05.2018  *emulation* key added
################################################################################

#access_restricted:  false
#emulation:          true
  
#debug:
#  status:           true

#mail:
#  bcc:              foo@gmail.com

period:             1.day
time_slot:          15.minutes